version: '3.0'

# 容器时区
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd --http-address 0.0.0.0:4161
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      uto:
        aliases:
          - nsqlookupd
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -tcp-address=0.0.0.0:4151 -http-address=0.0.0.0:4155
    depends_on:
      - nsqlookupd
    ports:
      - "4155:4155"
      - "4151:4151"
    networks:
      uto:
        aliases:
          - nsqd
  etcd-1:
    container_name: etcd1
    image: quay.io/coreos/etcd:v3.3
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 2379
    volumes:
      - ${PHP_WORK_SPACE}/etcd1:/etcd_data
    networks:
      uto:
        aliases:
          - etcd
  etcd-2:
    container_name: etcd2
    image: quay.io/coreos/etcd:v3.3
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://etcd-2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-2:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 2379
    volumes:
      - ${PHP_WORK_SPACE}/etcd2:/etcd_data
  etcd-3:
    container_name: etcd3
    image: quay.io/coreos/etcd:v3.3
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://etcd-3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-3:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2379:2379"
    volumes:
      - ${PHP_WORK_SPACE}/etcd3:/etcd_data

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      uto:
        aliases:
          - nsqadmin
  networks:
    uto: