version: '3.0'

# 容器时区
services:

  php:
    image: helinhan/php7.2:latest
    restart: always
    volumes:
      - ./php72.conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./nginx-php72/web.conf:/etc/nginx/conf.d/web.conf
      - "${WORK_SPACE}:/data"
    ports:
      - 80:80
      - 443:443
    networks:
      uto:
        aliases:
          - workspace

  redis:
    image: redis:4.0.1
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DATA_DIR}:/redis/data:z
    hostname: redis
    privileged: true
    restart: always
    command: ['--appendonly', 'yes', '--port', '6379', '--protected-mode', 'no','--requirepass', '${REDIS_PASSWORD}']
    networks:
      uto:
        aliases:
          - redis

  mysql:
    image: mysql:5.7
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      uto:
        aliases:
          - mysql

networks:
  uto: