version: '3.4'
services:
  api:
    image: helinhan/swoft:v1
    container_name: api
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
#      - mysql
#      - redis
#      - rabbitmq
    ports:
      - "81:80"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    volumes:
      - ${WORKSPACE}/dms/api:/home/www/api
    command: ["php","/home/www/api/bin/swoft","http:start"]

  user:
    image: helinhan/swoft:v1
    container_name: user
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
#      - mysql
#      - redis
#      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3
    volumes:
      - ${WORKSPACE}/dms/user:/home/www/user
    command: ["php","/home/www/user/bin/swoft","rpc:start"]

  order:
    image: helinhan/swoft:v1
    container_name: order
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
#      - mysql
#      - redis
#      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4
    volumes:
      - ${WORKSPACE}/dms/order:/home/www/order
    command: ["php","/home/www/order/bin/swoft","rpc:start"]

  pay:
    image: helinhan/swoft:v1
    container_name: pay
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
#      - mysql
#      - redis
#      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.5
    volumes:
      - ${WORKSPACE}/dms/pay:/home/www/pay
    command: ["php","/home/www/pay/bin/swoft","rpc:start"]

  common:
    image: helinhan/swoft:v1
    container_name: common
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
#      - mysql
#      - redis
#      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.6
    volumes:
      - ${WORKSPACE}/dms/common:/home/www/common
    command: ["php","/home/www/common/bin/swoft","rpc:start"]

  consul:
    image: consul:latest
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
    networks:
      mynetwork:
        ipv4_address: 172.20.1.1


networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16