version: '3.4'
services:
  api:
    image: swoft:v1
    container_name: api
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
      - mysql
      - redis
      - rabbitmq
    ports:
      - "81:80"
    networks:
      mynetwork:
        ipv4_address: 192.168.0.2
    volumes:
      - ${WORKSPACE}/api:/home/www/api
    command: ["php","/home/www/api/bin/swoft","http:start"]

  user:
    image: swoft:v1
    container_name: user
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
      - mysql
      - redis
      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 192.168.0.3
    volumes:
      - ${WORKSPACE}/dms/user:/home/www/user
    command: ["php","/home/www/user/bin/swoft","rpc:start"]

  order:
    image: swoft:v1
    container_name: order
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
      - mysql
      - redis
      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 192.168.0.4
    volumes:
      - ${WORKSPACE}/dms/order:/home/www/order
    command: ["php","/home/www/order/bin/swoft","rpc:start"]

  pay:
    image: swoft:v1
    container_name: pay
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
      - mysql
      - redis
      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 192.168.0.5
    volumes:
      - ${WORKSPACE}/dms/pay:/home/www/pay
    command: ["php","/home/www/pay/bin/swoft","rpc:start"]

  common:
    image: swoft:v1
    container_name: common
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
      - mysql
      - redis
      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 192.168.0.6
    volumes:
      - ${WORKSPACE}/dms/common:/home/www/common
    command: ["php","/home/www/common/bin/swoft","rpc:start"]

  gts:
    image: swoft:v1
    container_name: gts
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - consul
      - mysql
      - redis
      - rabbitmq
    ports:
      - "18306"
    networks:
      mynetwork:
        ipv4_address: 192.168.0.7
    volumes:
      - ${WORKSPACE}/dms/gts:/home/www/gts
    command: ["php","/home/www/gts/bin/swoft","process:start"]
  consul:
    image: consul
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
    networks:
      mynetwork:
        ipv4_address: 192.168.1.1

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=dlyun2019
    restart: always
    ports:
      - "3306:3306"
    networks:
      mynetwork:
        ipv4_address: 192.168.1.2
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOGS_DIR}:/logs
      - ${MYSQL_CONF_DIR}:/etc/mysql/conf.d

  redis:
    image: redis:5.0.1
    container_name: redis
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    command: redis-server --appendonly yes --requirepass '${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    networks:
      mynetwork:
        ipv4_address: 192.168.1.3
    volumes:
      - ${REDIS_DATA_DIR}:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      mynetwork:
        ipv4_address: 192.168.1.4
    volumes:
      - ${RABBITMQ_DATA_DIR}:/var/lib/rabbitmq
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16