version: '2.1'
services:
  yapi:
    image: mrjin/yapi:latest
    container_name: yapi
    environment:
      - VERSION=1.8.7
      - LOG_PATH=/tmp/yapi.log
      - HOME=/home
      - PORT=3000
      - ADMIN_EMAIL=linhanhe@dalongyun.com
      - DB_SERVER=mongo
      - DB_NAME=yapi
      - DB_PORT=27017
    restart: always
    ports:
      - 3000:3000
    privileged: true
    volumes:
      - /Users/galen/data/yapi/log:/home/vendors/log # log dir
      - ./config.json:/home/config-tpl.json
      - ./entrypoint.sh:/bin/entrypoint.sh
    depends_on:
      - mongo
    entrypoint: "bash /wait-for-it.sh mongo:27017 -- entrypoint.sh"
    networks:
      yapi-net:
        aliases:
          - yapi

  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - /Users/galen/data/mongo:/data/db #db dir
    networks:
      yapi-net:
        aliases:
          - mongo

  nginx:
    image: nginx:1.14.0
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web.conf:/etc/nginx/conf.d/web.conf
    ports:
      - 80:80
    networks:
      yapi-net:
        aliases:
          - nginx

networks:
  yapi-net: