version: '3.0'

# 容器时区
services:

  php56:
    image: helinhan/php5.6:dl
    container_name: php56
    restart: always
    volumes:
        - ./php56.conf/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ${WORK_SPACE1}:/data/dly:cached
        - ${WORK_SPACE2}:/data/helinhan:cached
    networks:
      uto:
        aliases:
          - workspace56

  nginx:
    image: nginx:1.14.0
    container_name: nginx
    restart: always
    volumes:
      - ./nginx-php72/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-php72/web.conf:/etc/nginx/conf.d/web.conf
      - ${WORK_SPACE1}:/data/dly:cached
      - ${WORK_SPACE2}:/data/helinhan:cached
    ports:
      - 80:80
    networks:
      uto:
        aliases:
          - nginx

  php72:
    image: helinhan/php7.2:latest
    container_name: php72
    restart: always
    volumes:
      - ./php72.conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ${WORK_SPACE1}:/data/dly
      - ${WORK_SPACE2}:/data/helinhan
    ports:
      - 9501:9501
    networks:
      uto:
        aliases:
          - workspace72

  php73:
    image: helinhan/php7.3:dev
    container_name: php73
    restart: always
    volumes:
      - ${WORK_SPACE1}:/data/dly:cached
    networks:
      uto:
        aliases:
          - workspace73

#  redis4.0:
#    image: redis:4.0.1
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ${REDIS_DATA_DIR}:/redis/data:z
#    hostname: redis
#    privileged: true
#    restart: always
#    command: ['--appendonly', 'yes', '--port', '6379', '--protected-mode', 'no','--requirepass', '${REDIS_PASSWORD}']
#    networks:
#      uto:
#        aliases:
#          - redis


#  mysql5.7:
#    image: mysql:5.7
#    container_name: mysql
#    restart: always
#    privileged: true
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#      - ${MYSQL_DATA_DIR}:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    networks:
#      uto:
#        aliases:
#          - mysql

#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    environment:
#      - APP_ENV=dev
#      - TIMEZONE=Asia/Shanghai
#      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
#      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
#    restart: always
#    volumes:
#      - ${RABBITMQ_DATA_DIR}:/var/lib/rabbitmq
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    networks:
#      uto:
#        aliases:
#          - rabbitmq

networks:
  uto: