version: '3.0'

# 容器时区
services:

  php56:
    image: helinhan/php5.6:latest
    restart: always
    volumes:
      - ./php56.conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./nginx-php56/web.conf:/etc/nginx/conf.d/web.conf
      - "${WORK_SPACE1}:/data/styd"
      - "${WORK_SPACE2}:/data/helinhan"
    ports:
      - 8080:80
    networks:
      uto:
        aliases:
          - workspace-php56

  php71:
    image: helinhan/php7.1:latest
    restart: always
    volumes:
      - ./php71.conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./nginx-php71/web.conf:/etc/nginx/conf.d/web.conf
      - "${WORK_SPACE1}:/data/styd"
      - "${WORK_SPACE2}:/data/helinhan"
    ports:
      - 8081:80
    networks:
      uto:
        aliases:
          - workspace-php71

  php72:
    image: helinhan/php7.2:latest
    restart: always
    volumes:
      - ./php72.conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./nginx-php72/web.conf:/etc/nginx/conf.d/web.conf
      - "${WORK_SPACE1}:/data/styd"
      - "${WORK_SPACE2}:/data/helinhan"
    ports:
      - 8082:80
    networks:
      uto:
        aliases:
          - workspace-php72

  redis4.0:
    image: redis:4.0.1
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DATA_DIR}:/redis/data:z
    hostname: redis
    privileged: true
    restart: always
    command: ['--appendonly', 'yes', '--port', '6379', '--protected-mode', 'no','--requirepass', '${REDIS_PASSWORD}']
    networks:
      uto:
        aliases:
          - redis

  mysql5.7:
    image: mysql:5.7
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      uto:
        aliases:
          - mysql

networks:
  uto: