version: '3.0'

# 容器时区
services:
  php5.6:
    image: helinhan/php5.6:latest
    environment:
      - no_proxy=${NO_PROXY}
    restart: always
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/web.conf
      - "${PHP_WORK_SPACE}:/data/styd"
    ports:
      - 8082:80
      - 19002:9000
    networks:
      uto:
        aliases:
          - php5.6

networks:
  uto: